from typing import *

class Rank:
    def __init__(self) -> None:
        self.largestCount = 0
        self.leadingTeams = set()
        self.teamCounts = {}

class Solution:
    def rankTeams(self, votes: List[str]) -> str:

        ranks = [Rank() for _ in range(len(votes[0]))]
        for vote in votes:
            for i, team in enumerate(vote):
                rank = ranks[i]
                
                if team in rank.teamCounts:
                    rank.teamCounts[team] += 1
                else:
                    rank.teamCounts[team] = 1
                
                if rank.teamCounts[team] > rank.largestCount:
                    rank.largestCount = rank.teamCounts[team]
                    rank.leadingTeams = {team}
                elif rank.teamCounts[team] == rank.largestCount:
                    rank.leadingTeams.add(team)

        for i, rank in enumerate(ranks):
            if len(rank.leadingTeams) > 1:
                if i == len(ranks) - 1:
                    rank.leadingTeams = {sorted(rank.leadingTeams).pop()}
                    continue
                for j in range(i+1, len(ranks)):
                    nextRank = ranks[j]
                    for team in rank.leadingTeams:
                        if team in nextRank.teamCounts:
                            rank.teamCounts[team] += nextRank.teamCounts[team]
                        if rank.teamCounts[team] > rank.largestCount:
                            rank.largestCount = rank.teamCounts[team]
                            rank.leadingTeams = {team}
                        elif rank.teamCounts[team] == rank.largestCount:
                            rank.leadingTeams.add(team)
                    if len(rank.leadingTeams) == 1:
                        break
                    elif j == len(ranks) - 1:
                        rank.leadingTeams = {sorted(rank.leadingTeams).pop()}

        ans = ''
        for rank in ranks:
            ans += rank.leadingTeams.pop()

        return ans

class Solution2:
    def rankTeams(self, votes: List[str]) -> str:

        scores = {}

        for vote in votes:
            weight = 1
            for i, team in enumerate(reversed(vote)):
                if team in scores:
                    scores[team] += weight
                else:
                    scores[team] = weight
                
                weight *= 10
        
        sortedScores = sorted(scores.items(), key= lambda x: (x[1], -ord(x[0])), reverse=True)
        sortedTeams = [x[0] for x in sortedScores]

        ans = ''.join(sortedTeams)
        
        return ans


s = Solution2()
s.rankTeams(["PGAOFXIKYJVSLTUHCZQRE","LSIAPTHYCGURKEZXJOFQV","UGSARZICOXYPHTQFJKVEL","XIAOKSVGRJCHQZUETLYPF","OHRXPGEVUYCSKZILQATFJ","UHFSCZVKIELGOQJYRXPAT","QECXVZKJTLIYHUFRGOSAP","RJGAZIKPEVUSTOXFQYCHL","XRFGPAQSJOETHVCZIKLUY","ZCTQOVRFKXJGEALSHIYUP","QGTEHXCJRIPSUZALOYFVK","GIHXVJPQYOSZFRKLEUTAC","LURXHFECKZSYPTQGAOJVI","TFUKZELVARQCXIYPJHGSO","FIPYTACSXZKLRGOHJVEQU","ZKJQOGHVURAISXFLPYECT","XKOJAHVQUCETFPRYZGLSI","TUKZAVIFXEGQCSOLJRPHY","OSIPCFVRLAYKEHZTJGUQX","OYAQTCEKLGPRZVISUXFHJ","SKHCXEZLTFVQOIUPRAJGY","CRZPAEILFTOKUJVGXHQYS","OQVLPEYZFIGJRKUSXAHTC","VQTXURZKAPGHEIFCOLSJY","YVRZKXSOAEIPUQJHGCFLT","YEJTGFQPOZLCARSUIKVHX","XKASIECRHVQFPULZTOGJY","KAQVYSZLTFXCGEJIRUHOP","IYJXCUTOAPQKHEZFGRVSL","OIEPRLZGUVQHSYJAFTXCK","CIGVAZLKORXQYPHTEUSFJ","UVTCJFQOGXIZHLKYRASEP","FCVOYSJHZLKATXRIUPQGE","TJLQFSRKIUGPCVZHOEAXY","FUHLSRGTCOXAEZVQIYKPJ","CAGRHEUQZISYKXLFVPJOT","LASKUHEPJQXRCTZOVIYFG","IGKJSYLVFCUXETRAHZQPO","UZGXPIAFVOSLKRYQJTCHE","VKELXAFPOGSRIZCUQYTHJ","GCTJEUFRVLKAIOYSHZXQP","PHUOAXLYFTCRSEQIKGJZV","XLQYSIJHTREFPOKCUGVAZ","LUZXHQKIATOCGJYPFSVRE","XILVQZAFUKECYJGTPHSOR","GCQFHJKTAERVPIYUSZOLX","ZPRILGHYXTFVSQCAUKEOJ","SLFTYQPZKUAIVGRHEOCXJ","FCUVEOKHGZQSYJRXPAILT","AKZJRQCPVHYGSXLFITUOE","OKVEHCXPYRUGIAZJQFSLT","YZVHPIGSLREJQCXOKFATU","QTCILUZFVYHSAPGJEKXRO","YXKJOPHIVGARUTZEFLSCQ","OZPXURLHEKFQTSIVJYGCA","YIVEGRJLTPOAZFCQSUXHK","VPQUXLYGACSITFKEJHORZ","AOEQLYPFZUXCKHSTVIJRG","IFYTULEXKZRCOHASQPJGV","TASULVYKZPOCGIHJERXFQ","RGXYZCHVEAPTJISQUFKOL","XKVRTHJSLOZPIAYUEQGFC","EYIRXQTCUPHSVJFZLAKOG","ZRJSTQIGPELKUCHAOYVFX","EIXJPTZGRKVYCUFAOHQLS","LRSGUJZYXCIVQOAHTFPEK","ZHLOESVGIARXCUQYKPFJT","ZKQLVGOIFASTPUHYJRCXE","ZLPJQYTXEGAFHOSRCIUVK","ZVHYQJXCGTAFKLEISOPUR","KZGLYEQAURFHSXIVPTJCO","TIXPAYEKJLVGCQRUHOSZF","ESORYCVXLPKZFQJAUGIHT","FAJTCHORZGLIKXYSVUPQE","AOXHJEZFYLIQCPRVTSGKU","IZVAPOTEHCJQLKRGFUSXY","RTVYZHSIPGCEKJQUAXFOL","GSHOKEXAZCIQYTRJFVLPU","SXZLKIUGEVCPFHTQJARYO","QPCOTHISGLKYJFUAZXVRE","XPUEYATJHCOLVGSQRIZKF","GIKSZFHEQLTCVXJAYOPUR","RFSOEJPUAGKYHZIQCTLXV","UFHXJLITQPEGCKOSZYRAV","ZVQAFGXEIRSTPJYLHCOKU","ZITVJLSOAUGPCFYXHRQKE","RCZOIPEXFJAQGSYVLKHUT","TUHVJROCXIGEPLQAZYKSF","ATQJGKUIPLZXEYCRSOVFH","TVHYLSRAKIXJFGEPOZUCQ","CAPHZLGXQSIRTJYFOKEVU","FAYOKHEUZIRJXQTVGCSPL","IJCRUHVAPFYKGXLTSOQEZ","ZKIJLQEAUVHFTYRXCSGOP","ALFTJSRXUQPIOVZCYHEKG","ZASIVJQYUCRPEKGLTXFHO","OICQXZPEFUSTVALKGYRJH","ZOKVPHUXGRQIJCSEYALFT","FKACPHOSIREGUTYLJXZVQ","IZXOREFGSLPKUHAYCVTJQ","UVXZTCFAQEYLORSKHPJIG","PKVQCYSTLHRZIFAUEXJGO","IRFZSKGEHQVOLXCTJUPAY","XYHPVOTILEAUZJGSKQCRF","ERXJLFZQIGHPCSTYKUVOA","SZTIFCGVEKUJYPAOQXHRL","JPTGQOEYFIKURCVHXALZS","URJGTXZKICAOQSLVEYHFP","ZERGKOLTSUIXJFACVQHPY","GQCVAJYIKRZLTPSFHOUEX","OKRCTSGLZXQJEHPFVYUIA","GUKXARTQFYSCVEZIOJHLP","UTCIRLFHGJOSYZVPQKEAX","JPIOVSFZHUTQKCERXAGLY","LKJEGOHRTYQFXUSCVIPZA","LSETPUAHZYOICVRGJFXKQ","OPGHRVUXQEYLZFISTJKCA","VOKCSGFTXZEIRYALHJPQU","POTXFYCQIVZHLGJERAUSK","FAUIECXOYPLRHJKTSZQVG","XFAETYRCJUGVPQZOKSLHI","LGCVYIAZRFJSHQXTKUOPE","YKATQFIURCHPLSVGJEXOZ","IRUHTAXVYZKFPSEOJCLGQ","TAVEXIHLPOGSZRCJFQKUY","GFACLJSETKIXRZUYHVPOQ","XTJKSAZIQYRCLPGOHUFEV","GSFTZLJCVKRYUOXAQIEPH","GIOLPRXHCSUFKAVTJZEQY","SFCRPVGYKOUZJALQEXHIT","EUTOKQGFCLRAVZPJYSXHI","UOYSHGLTPZXRICFJEKAVQ","OTZIGVXSQHCPRYUKELAJF","SGZOEHLKYUPXCJRFTAVQI","JOCVZLGSUIAHPFKYTQERX","ZFSRJULQGKIOXEPYHTACV","FGSJCIYXHEAZTOLUKRVQP","YXHICZVFTSQJKLPOURGAE","XALRUOHJZYVEGQPKCSFIT","KCIJLRXYHAESGFQUOPVZT","AUTSXLECOGPZIHRVYQKFJ","GIZRAKEVOXLTCJSUHQPFY","ZKUPCORTFYEIAGJQXVLHS","JALHXZQIYSUROPCEGKVFT","KUIGTSQAJEOZYPCFHLXRV","LXICRFZJEUVYASPKQHTOG","EFUPZKRXLCAVJGQITHOSY","EUYGQKARZJVHLIPFCOSTX","AOXTKHRYLJZQEUCSPGVIF","SHUTLZEGRJYPCVAFXQOKI","GUZTAXQLKIRFYEOHJSPVC","RGOZPAXLYVJSHFICKTQUE","ASCHFQVTRLEKYUZIXGJPO","CQFRUSIXLOZPVJTGYAHEK","VGYURSHEXIKCFOAPTQLJZ","VFQCGPEAYISTXKORLUJHZ","UZJOYGVRETFSPLQAIKHCX","JKQRZFXICESTHPGOUYVAL","XGFYRJKCVTESZPHLQUIOA","YEPGFRALQOKJTXSZCIUVH","CXHPFAYKVZQORLJUTEGSI","PXHACSGJUILTYVQRFKEOZ","RSILHFAYCQJKVUGZTPXOE","IKAEOXFVPHSLRCQGZYJTU","GVKRJFLXZUOSAEIYPTCQH","TEXZOUVPICHGFLRYSQKAJ","JCEHLTRZQVFOPUSIKGYXA","GFLJHYXEAQTOPSKIUZVRC","ZGKJFVEAUHIXRTCLSPYQO","GXOTELHIQKUAFSVRPZYCJ","XRZEUGOIVAKSYPHJQCFLT","PYQVXGHSAKLRFTEZOUICJ","QGHOCVKFEPUTSRAIJYZLX","YRQVOLKJGFIXHEPCTUAZS","CTXYFQVZASEHPIOUJGRLK","GIZHRVQLJEYAKTSUCOPXF","XIGKSCLTRYJHZFUOQAPVE","RYCXPSEGIFAULKZTQJVHO","PXEQTGYSHICLAVRUZKJOF","AERXGTIHLUZSFKQYVPCJO","SKTPVFXILUZHYCEJAQROG","OCQUZKSJYLIVARFEHTPGX","ISZXFQUKHJOTCREPGYALV","LOSTQCIRZFVGYKPEAJHUX","QPFTRGUKOIVXESYCJZLAH","PXSUEIVOHZCKJFQLTGRAY","QYLRCVJOPEXGUTZKSAIFH","RJQPOFKXIHUZYVETCSLAG","HTFJEAISYQZUXLCGVPORK","ECGFLAHQJPORITXYUKVZS","FJGAIOSPTVXUZYHLQKERC","GEQLKYPICTUAFRSOVXZHJ","CGJHEZKSTIUQOFVRYXLAP","XYJSGTIKOVUFERLHCPAQZ","LQFVECITUGXHOYJKASRZP","HYGJQFUPZVORSKICLETXA","ACTXZRUYPOJLIEFSKQVGH","PHOLYCFUKRASEGTVQZXIJ","RTUOEZHPSKAFXLQYICVGJ","RAPTGQIJOSEFZUKVXCLHY","EUAKTQLJFOHCPSYVGRZXI","TYUPHSXVEZKIFQACRLJGO","ZHOEAIULSVJQKGRYFTXPC","CPEUIGVRFSOZAKYHQLTJX","ZCOEYRHVQFLSJIXUATGKP","FGSCJZKUTRVOLEYHQIPAX","SPKIGAUVQJXZYEHROCFTL","ITQVPZLEOGJUHKXRYFASC","GSAFTOHJQCYLUVPZEXRKI","ZPFKXLUJSRCAHOGYTVIEQ","QIFYPTAJELCSOXUKRZGVH","JFGZCQAELXKOIUHYRSTVP","TIGPACUOYZJHXKSVQEFRL","EATKLFGOCZVQHXRYSJIPU","SPOJYHVQXGZELUACKFITR","YTVIQXEZUJRFGCOLKSAPH","SPGHEQZJVXKIOAYLRUCFT","RFXCSUZIJAQTELHKVPOGY","PHXJESZRGFLKOAVIQUTYC","GUYCOKILATEJZXHFPRSVQ","GQTUFLAKCPVRYIOHXEZJS","AYVCGFTIQKLZSXEPHRJUO","EAXRUTPZVHCGLISYQFKOJ","SUVFHQGRLXEZAYJTCIPKO","PXKTOGRLHQAJFZCIYUSVE","ZGXYPLOSRCTAVFEUIQKHJ","OKEHXFQSIZGCRJLPATYUV","YXQILGVKPJOUTAZRCSEHF","TYQAGXSCZVKLJEOIHPURF","ELAJZPXRIFQVSGKTOCUHY","YIPXUJHGACTVQEKSOZRLF","ZPAGUYLVSRCIKOJXFTEQH","LYKIJURAEGVZSFPXHCOTQ","EULYFIOJTGXZQCPARHKSV"])
print('hello')
